### ISSUE TITLE
Quest의 간단한 조회 기능 추가

### ISSUE THREAD

**Issue by kukjun** [TestMatchingPlatform/backend#2]
* Quest의 정보 중 간단한 조회 기능을 추가한다.
* 필요한 내용은 제목, 카테고리 종류, 제작한 ntc, 모집 시작 시간, 모집 마감 시간, 수행 가능 인원, 보상 금액
* 매개변수는 quest id, 반환 값은 Quest이지만, 필요한 내용만 작성되어 있는 객체이다.

**Comment by heeyoungs** [comment]
![image](https://user-images.githubusercontent.com/71438556/169519663-8dce744e-7f9a-4fcf-84bc-5990a6cfb095.png)
