### ISSUE TITLE
Quest 진행 상태 조회

### ISSUE THREAD

**Issue by kukjun** [TestMatchingPlatform/backend#3]
* 매개변수 없음
* 반환값은 진행 상태를 나타내는 int
* 0 모집기간, 1 진행기간, 2 수정기간

**Comment by heeyoungs** [comment]
![image](https://user-images.githubusercontent.com/71438556/169519752-c884891b-5b1b-42ea-8ca7-e271b2b3f6e9.png)

**Comment by heeyoungs** [comment]
일단 보류(이건 못하는게 아니라 필요 여부 떄문에)

**Comment by kukjun** [comment]
프로젝트 이슈가 구체적이지 못해서 Closed
